name: mern-app

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - mern-app
    restart: unless-stopped
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 4000:4000
    networks:
      - mern-app
    depends_on:
      - mongo
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - mern-app
    ports:
      - 3000:3000
    depends_on:
      - api
  redis-server:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - mern-app

volumes:
  mongo_data:
networks:
  mern-app:
    driver: bridge